// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


function code(someCode) {
  switch (someCode) {
    case 0 : 
        return 200;
    case 1 : 
        return 201;
    case 2 : 
        return 400;
    case 3 : 
        return 401;
    case 4 : 
        return 500;
    
  }
}

var basicHeader = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Credentials": true
};

function resp(someCode, body) {
  return {
          statusCode: code(someCode),
          headers: basicHeader,
          body: JSON.stringify(body)
        };
}

function responseOk(param) {
  return resp(/* Ok */0, param);
}

function responseAddOk(param) {
  return resp(/* Created */1, param);
}

function responseBadRequest(param) {
  return resp(/* BadRequest */2, param);
}

function responseNotAuth(param) {
  return resp(/* Unauthorized */3, param);
}

function responseInternalErr(param) {
  return resp(/* InternalServerError */4, param);
}

function responseErrWithMsg(msg) {
  return responseBadRequest("{\"message\": " + (String(msg) + "}"));
}

var responseAddOperationOk = responseBadRequest("{\"result\": \"ok\"}");

var responseErr = responseBadRequest;

exports.code = code;
exports.basicHeader = basicHeader;
exports.resp = resp;
exports.responseOk = responseOk;
exports.responseAddOk = responseAddOk;
exports.responseBadRequest = responseBadRequest;
exports.responseNotAuth = responseNotAuth;
exports.responseInternalErr = responseInternalErr;
exports.responseErr = responseErr;
exports.responseErrWithMsg = responseErrWithMsg;
exports.responseAddOperationOk = responseAddOperationOk;
/* responseAddOperationOk Not a pure module */
